### ISSUE TITLE
Invariant Violation: requireNativeComponent: "WheelCurvedPicker" was not found in the UIManager.

### ISSUE THREAD

**Issue by lutakyn** [TronNatthakorn/react-native-wheel-pick#1]
I have implemented your library in my project but the error is get is " **Invariant Violation: requireNativeComponent: "WheelCurvedPicker" was not found in the UIManager.**" I am using expo and I have ejected the project but the code doesn't work and breaks my app.
How can I solve this since I won't be using any android or swift code in my project. 
I also want to know if I have to eject the project before I can use the library.Any help?

   `<Picker
                    style={{ backgroundColor: 'white', width: 300, height: 215 }}
                    selectedValue='item4'
                    pickerData={['item1', 'item2', 'item3', 'item4', 'item5', 'item6', 'item7']}
                    onValueChange={value => { }}
                    itemSpace={30} 
                  />`

**Comment by TronNatthakorn** [comment]
This library does not support expo this time.
I never use expo, too.
If you have problem about expo eject I think this can help. (I'm not sure.) @lutakyn 

https://forums.expo.io/t/react-native-project-eject/1494

`When you eject and add native code you will need to build your native app binaries yourself with Xcode or Android Studio. The Expo client loads only JS (no native code) so this is a technical limitation`

**Comment by lutakyn** [comment]
Thank you. But how will I be able to remove the two lines that shows the centered item in the wheel.Any help?

**Comment by TronNatthakorn** [comment]
**Support Line style in future. :( Pull request welcome **

**Comment by Abdiel49** [comment]
I had the same problem using version `1.2.2` with react native version `0.65.0`, but it works fine with version `1.2.0` :
"react-native-wheel-pick": "1.2.0",

```sh
npm install react-native-wheel-pick@1.2.0 --save-dev --legacy-peer-deps
```
