### ISSUE TITLE
Warning: DatePickerIOS has been merged with DatePickerAndroid

### ISSUE THREAD

**Issue by psolom** [TronNatthakorn/react-native-wheel-pick#10]
Get warning at react-native 0.61

Warning: DatePickerIOS has been merged with DatePickerAndroid and will be removed in a future release. It can now be installed and imported from '@react-native-community/datetimepicker' instead of 'react-native'

**Comment by zmnv** [comment]
@TronNatthakorn this is very important thing, can you replace datapicker from react-native to react community's module?

**Comment by bahtiyarerden** [comment]
@TronNatthakorn is there an any update here?

**Comment by TronNatthakorn** [comment]
Fixed. Please update to latest version.
