### ISSUE TITLE
Change text color

### ISSUE THREAD

**Issue by DaniSido** [TronNatthakorn/react-native-wheel-pick#14]
Hi, 
How can I change the color of the text? 
I also tried to modify the plugin source code but could not find a workaround.

Thank you very much.
Dani

**Comment by sobanfly** [comment]
any answer?

**Comment by sobanfly** [comment]
@DaniSido 
`itemStyle={{color: 'color hex value'}}`

**Comment by DaniSido** [comment]
> @DaniSido
> `itemStyle={{color: 'color hex value'}}`

Thank you very much!!
