### ISSUE TITLE
Error: PickerIOS has been removed from React Native.

### ISSUE THREAD

**Issue by cnrsbtogll** [TronNatthakorn/react-native-wheel-pick#15]
Error: Requiring module node_modules/react-native-wheel-pick/src/index.js, which threw an exception: Invariant Violation: PickerIOS has been removed from React Native. It can now be installed and imported from @react-native-picker/picker instead of react-native. See https://github.com/react-native-picker/picker

**Comment by machowski** [comment]
having same issue, could PR be reviewed and accepted?

**Comment by TronNatthakorn** [comment]
Fixed. Please update to latest version.
