### ISSUE TITLE
Please update the front page

### ISSUE THREAD

**Issue by Vasault** [TronNatthakorn/react-native-wheel-pick#19]
So we can see all the props that you can use with this component, all i see are examples

**Comment by TronNatthakorn** [comment]
For documentation please pull request for README.MD.
For bug please explain more detail.

**Comment by ChrisSimoniMBT** [comment]
You should update the readme though. I don't believe `pickerData` is a prop anymore and you need to use the `<Picker.Item />` component as children. Unless, I am wrong.
