### ISSUE TITLE
How to change selected Item color , currently not find any props for it. 

### ISSUE THREAD

**Issue by ForamPattha** [TronNatthakorn/react-native-wheel-pick#22]
![Simulator Screen Shot - iPhone 13 - 2022-07-26 at 17 06 42](https://user-images.githubusercontent.com/66566727/180998681-95ad1465-0a84-42f2-b2a9-45c4e8586701.png)
 
I want to change that rectangle selected item color .

**Comment by TronNatthakorn** [comment]
@ForamPattha for `iOS` you cannot change color. This is default behavior of iOS.

for `android` you can use `selectBackgroundColor`

**Comment by ForamPattha** [comment]
Yes , but is it possible to change that background color in ios  because  I want same behaviour for both platform so how it's possible using this library . can you please share your idea regarding this .
