### ISSUE TITLE
Android: fontFamily, fontWeight

### ISSUE THREAD

**Issue by Aleksandern** [TronNatthakorn/react-native-wheel-pick#23]
Hello.

Is there a way to set `fontFamily` and `fontWeight` for Android?

Thanks.

**Comment by TronNatthakorn** [comment]
I am so sorry. This library is not support. 

These are default support for android.

[ReactWheelCurvedPickerManager.java](https://github.com/TronNatthakorn/react-native-wheel-pick/blob/master/android/src/main/java/com/tron/ReactWheelCurvedPickerManager.java)

If you want to use `fontFamily` and `fontWeight`, you need to edit android native code for make this library support.
