### ISSUE TITLE
how to make two columns

### ISSUE THREAD

**Issue by akshPairroxz** [TronNatthakorn/react-native-wheel-pick#24]
hello , i would like to know that how can i create two columns using it , as i am looking to create month-year picker using this library.

**Comment by TronNatthakorn** [comment]
This library is not support for only month-year.
You can use just normal picker instead.

(Because every years always have twelve months.)

```
<Picker pickerData={['2020', '2021', .......]} />
<Picker pickerData={['Jan', 'Feb', .......]} />
```
