### ISSUE TITLE
How can I use in Expo?

### ISSUE THREAD

**Issue by somilmathur** [TronNatthakorn/react-native-wheel-pick#9]
Invariant Violation: Invariant Violation: requireNativeComponent: "WheelCurvedPicker" was not found in the UIManager.

**Comment by TronNatthakorn** [comment]
This project not support expo. 

https://github.com/TronNatthakorn/react-native-wheel-pick/issues/1

**Comment by sleekLancelot** [comment]
> to use this in Expo, you will have to create Expo development build

Hi, where you able to get it to work on a dev-client? I use a dev client and after another dev build I still get an error.
`Invariant Violation: requireNativeComponent: "RNCPicker" was not found in the UIManager.`

**Comment by sleekLancelot** [comment]
> > to use this in Expo, you will have to create Expo development build
> 
> Hi, were you able to get it to work on a dev-client? I use a dev client and after another dev build I still get an error. `Invariant Violation: requireNativeComponent: "RNCPicker" was not found in the UIManager.`

Turns out the error was from another package 'react-native-swift'. I unistalled it, created another build and it worked.
